<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta property="og:site_name" content="Doug's Compiler Corner"/><link rel="canonical" href="https://www.douggregor.net/posts/swift-for-cxx-practitioners-error-handling"/><meta name="twitter:url" content="https://www.douggregor.net/posts/swift-for-cxx-practitioners-error-handling"/><meta property="og:url" content="https://www.douggregor.net/posts/swift-for-cxx-practitioners-error-handling"/><title>Swift for C++ Practitioners, Part 6: Error Handling | Doug's Compiler Corner</title><meta name="twitter:title" content="Swift for C++ Practitioners, Part 6: Error Handling | Doug's Compiler Corner"/><meta property="og:title" content="Swift for C++ Practitioners, Part 6: Error Handling | Doug's Compiler Corner"/><meta name="description" content="Swift for C++ Practitioners, Part 6: Error Handling"/><meta name="twitter:description" content="Swift for C++ Practitioners, Part 6: Error Handling"/><meta property="og:description" content="Swift for C++ Practitioners, Part 6: Error Handling"/><meta name="twitter:card" content="summary"/><link rel="stylesheet" href="/styles.css" type="text/css"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><link rel="shortcut icon" href="/images/favicon.png" type="image/png"/><link rel="alternate" href="/feed.rss" type="application/rss+xml" title="Subscribe to Doug's Compiler Corner"/></head><body class="item-page"><header><div class="wrapper"><a href="/" class="site-name">Doug's Compiler Corner</a><nav><ul><li><a href="/about">About</a></li><li><a href="/posts" class="selected">Posts</a></li></ul></nav></div></header><div class="wrapper"><article><p>Originally posted on 2024-04-14 18:09:00 +0000</p><p>Last updated on 2024-06-15 05:10:50 +0000</p><div class="content"><h1>Swift for C++ Practitioners, Part 6: Error Handling</h1><p>C++ has a few different mechanisms for handling errors. One is <a href="https://en.cppreference.com/w/cpp/utility/expected"><code>std::expected</code></a>, where the return type of a function is either the expected value or an error value. Another is <a href="https://cplusplus.com/doc/tutorial/exceptions/">exceptions</a>, which come with a whole host of downsides (we'll get there in a moment). Personally, I find that I end up hand-rolling something more like <code>std::expected</code> in C++ more often than not, and the experience isn't great.</p><p>Swift takes some of the syntax of C++ exceptions (<code>throw</code> and <code>catch</code>), but the underlying philosophy of error handling in Swift is a bit different from C++. To get to it, let's start by looking at some of the issues with C++ exceptions, as they will help inform the choices made in Swift.</p><h2>Issues with C++ exceptions</h2><p>Herb Sutter did quite an excellent job of laying out the issues with C++ exceptions in <a href="https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0709r4.pdf">P0709</a>. Rather than come up with my own formulation from scratch, I'll quote directly from his abstract and refine from there:</p><ul><li>¬ß4.1: C++ projects commonly ban exceptions, because today‚Äôs dynamic exception types violate the zero- overhead principle, and do not have statically boundable space and time costs. In particular, throw requires dynamic allocation and catch of a type requires RTTI.</li><li>¬ß4.2: Programs bugs are not recoverable run-time errors and so should not be reported as exceptions or error codes.</li><li>¬ß4.3: Allocation failure is not like other recoverable run-time errors and should be treated separately.</li><li>¬ß4.5: Some users don‚Äôt use exceptions because exceptional control flow is invisible.</li></ul><p>I think Herb missed one overarching problem, which is that C++ got the defaults wrong with respect to exceptions. In C++, a function is assumed to throw unless it is explicitly marked <a href="https://en.cppreference.com/w/cpp/language/noexcept_spec"><code>noexcept</code></a>(or <code>throw()</code> in the pre-C++11 beforetimes). This means that nearly every C++ function out there can throw, because only the most diligent C++ developer is going to carefully audit each function to make sure it is marked <code>noexcept</code>, and suffer the unexpected <a href="https://en.cppreference.com/w/cpp/error/terminate"><code>std::terminate</code></a> call if they got it wrong. The problem with getting this default wrong is that it undercuts everything else you'd like to fix with the C++ exceptions design. The space and time costs for exceptions (Herb's ¬ß4.1) might be perfectly acceptable if you only paid for them where you used exceptions, but because of throwing-by-default, you're paying those costs across the entire code base even if only a narrow portion of it actually uses exceptions. Additionally, you can't change the language to make exceptional control flow visible (Herb's ¬ß4.5) when the default is "everything throws", because exceptional control flow is <em>everywhere</em> in C++. And while you could eliminate <code>std::bad_alloc</code> (Herb's ¬ß4.3) to reduce the number of places that could automatically throw, it barely makes a dent in the user experience when everything is already assumed to throw.</p><p>Error handling is hard: it's hard to anticipate what failures can occur, hard to figure out how to respond appropriately to get back to a reasonable state after an error, and hard to simulate those errors in a test to be sure you got it right. A language needs to help you identify and deal with errors, and most-everything-can-throw does the opposite.</p><h2>Swift's approach to error handling</h2><p>Swift's error handling model is similar in spirit to C++: an error is thrown with <code>throw</code>, can propagate through multiple stack frames (tearing down local values and running <code>defer</code> blocks along the way), and is eventually caught with a <code>catch</code> block. Nearly any type can be thrown: the only constraint is that the type must conform to the <a href="https://developer.apple.com/documentation/swift/error"><code>Error</code></a> protocol. By default, errors in Swift are type-erased to <code>any Error</code>; see my prior post on type erasure if you want to learn more about type erasure.</p><p>The differences are mainly in the defaults, but they make a world of difference. A Swift function cannot throw unless it explicitly specifies that it <code>throws</code>, and memory allocation failure is not handled via a thrown error (Herb's ¬ß4.3), so the vast majority of Swift functions are non-throwing.</p><p>Thrown errors are checked at compile time: a throwing operation must be marked via the <code>try</code> keyword to make all of the control flow in code explicit (Herb's ¬ß4.5), and the thrown error must either be handled (e.g., with a <code>catch</code> block) or the enclosing function must be marked <code>throws</code> to allow the error to propagate out of it. The key goal here is that there should be <strong>no surprises</strong> in error handling: you know where errors originate and how they propagate, and while you can write bad error-handling code, it's hard to forget to write it at all, and you only do so when things can actually fail.</p><h3>An example</h3><p>Let's see Swift's error handling in action by writing a simple function to parse a string into an integer. Because I love generic programming, we're going to make it generic over any fixed-with integer type by turning it into an extension of the <a href="https://developer.apple.com/documentation/swift/fixedwidthinteger"><code>FixedWidthInteger</code> protocol</a>. But first, let's think about what can go wrong: the easiest thing that can go wrong is that one of the characters in the string isn't a digit. Let's capture that case in a new <code>Error</code>-conforming <code>enum</code> that will describe errors that occur during integer parsing:</p><pre><code><span class="keyword">enum</span> IntegerParseError: <span class="type">Error</span> {
  <span class="keyword">case</span> nonDigitCharacter(<span class="type">String</span>, index: <span class="type">String</span>.<span class="type">Index</span>)
}
</code></pre><p>We haven't talked about the <a href="https://developer.apple.com/documentation/swift/string"><code>String</code></a> type much, so allow me a slight digression...</p><blockquote><p><strong>Digression</strong>: A proper discussion of <code>String</code> could fill up its own post, so here's the short version: <code>String</code> is a fully Unicode-aware string type and always contains a valid Unicode string. It's generally best to form and manipulate them with string literals, string interpolations, or other high-level operations. For lower-level operations you can treat them as a collection of <a href="https://developer.apple.com/documentation/swift/character"><code>Character</code></a> instances. <code>Character</code> is about as far from the C++ <code>char</code> type as you can get, because it captures the notion of a <em>grapheme cluster</em>, which is the nearest approximation Unicode has to what a human would consider a single character on screen. This covers everything from simple ASCII characters to composed multi-byte sequences like flag emoji (üá∫üá¶) and family emoji (üë©‚Äçüë©‚Äçüë¶‚Äçüë¶).</p></blockquote><p>So, let's build our first iteration of a parsing function that takes a string and converts it to any fixed-width integer:</p><pre><code><span class="keyword">extension</span> <span class="type">FixedWidthInteger</span> {
  <span class="keyword">init</span>(parsing string: <span class="type">String</span>) <span class="keyword">throws</span> {
    <span class="keyword">self</span> = <span class="number">0</span>
    <span class="keyword">for</span> index <span class="keyword">in</span> string.<span class="property">indices</span> {
      <span class="keyword">let</span> char = string[index]
      <span class="keyword">guard let</span> digit = char.<span class="property">wholeNumberValue</span> <span class="keyword">else</span> {
        <span class="keyword">throw</span> <span class="type">IntegerParseError</span>.<span class="call">nonDigitCharacter</span>(string, index: index)
      }

      <span class="keyword">self</span> = <span class="keyword">self</span> * <span class="number">10</span> + <span class="type">Self</span>(exactly: digit)!
    }
  }
}
</code></pre><p>I chose to make this an initializer, so that it can be used as (e.g.) <code>Int8(parsing: string)</code>. The code itself walks through each of the indices in the string, extracting each character, turning it into a <a href="https://developer.apple.com/documentation/swift/character/wholenumbervalue">whole number value</a>, and accumulating the result into <code>self</code>. If at any point it finds a character that isn't a whole number value, it will <code>throw</code> an instance of <code>IntegerParseError</code> that describes what the problem is.</p><p>There is no error-handling code within this initializer, so it must be marked as <code>throws</code> to indicate that an error can propagate out of a call to the initializer. The Swift compiler will produce an error if the <code>throws</code> is missing.</p><p>Now, when we use this initializer, we will always need to acknowledge the error. For example, let's try to parse "1+23" into an <code>Int8</code>:</p><pre><code><span class="keyword">let</span> value = <span class="keyword">try</span> <span class="type">Int8</span>(parsing: <span class="string">"1+23"</span>)
</code></pre><p>The <code>try</code> must be present to indicate that an operation to its right can throw. Just as any code containing a <code>throw</code> must account for the error (by handling it or being <code>throws</code> itself), code containing a <code>try</code> must account for the error. This makes control flow due to errors explicit. Note that you can cover multiple throw sites with a single <code>try</code> if you'd like. For example:</p><pre><code><span class="keyword">let</span> (first, second) = <span class="keyword">try</span> (<span class="type">Int8</span>(parsing: firstString), <span class="type">Int8</span>(parsing: secondString))
</code></pre><p>is equivalent to</p><pre><code><span class="keyword">let</span> (first, second) = (<span class="keyword">try</span> <span class="type">Int8</span>(parsing: firstString), <span class="keyword">try</span> <span class="type">Int8</span>(parsing: secondString))
</code></pre><p>It's a matter of taste. My personal style leans toward the former, because if there's any kind of side effect in a subexpression that would need different control flow, I'm going to break that out into a separate statement anyway.</p><h3><code>do..catch</code> blocks</h3><p>So, we've seen that we can mark a function as <code>throws</code> to allow an error to propagate out of it, so how we can handle an error when we don't want it to propagate? In Swift, it's a <code>do..catch</code> block:</p><pre><code><span class="keyword">do</span> {
  <span class="keyword">let</span> value = <span class="keyword">try</span> <span class="type">Int8</span>(parsing: <span class="string">"1 + 23"</span>)
  <span class="call">print</span>(<span class="string">"Integer value is</span> \(value)<span class="string">"</span>)
} <span class="keyword">catch let</span> error {
  <span class="call">fatalError</span>(<span class="string">"Invalid input string:</span> \(error)<span class="string">"</span>)
}
</code></pre><p>Any errors thrown within the body of the <code>do</code> part of a <code>do..catch</code> block will be checked against each of the <code>catch</code> blocks, much like C++'s <code>try..catch</code>. In this example, we have a single <code>catch</code> block that catches any error. The error itself will be named <code>error</code> and have type <code>any Error</code>.</p><p>There can be multiple <code>catch</code> clauses, and they use the same pattern-matching syntax as <code>switch</code> statements, so we can match a particular error case if we want:</p><pre><code><span class="keyword">let</span> value: <span class="type">Int8</span>?
<span class="keyword">do</span> {
  value = <span class="keyword">try</span> <span class="type">Int8</span>(parsing: <span class="string">"1 + 23"</span>)
} <span class="keyword">catch</span> <span class="type">IntegerParseError</span>.<span class="call">nonDigitCharacter</span>(<span class="keyword">let</span> string, index: <span class="keyword">let</span> index) {
  <span class="call">print</span>(<span class="string">#"Non-digit character "</span>\#(<span class="string">string[index])" found in string "</span>\#(string)<span class="string">"."#)</span>
  value = <span class="keyword">nil</span>
} <span class="keyword">catch</span> {
  <span class="call">print</span>(<span class="string">"Unhandled error</span> \(error)<span class="string">"</span>)
	<span class="keyword">throw</span> error
}
</code></pre><p>Now when an <code>IntegerParserError.nonDigitCharacter</code> error is thrown, it will be matched against the first <code>catch</code>, with the <code>string</code> and <code>index</code> values of the error bound to the stored values.</p><blockquote><p><strong>Aside</strong>: I snuck another minor Swift feature into that <code>print</code> statement, raw string literals, which are written with <code>#"..."#</code>. Inside, double-quotes don't finish the raw string literal unless followed by a <code>#</code>, and the <code>\</code> is not an escaping character unless followed by the <code>#</code>. If you really want to use <code>"#</code> or <code>\#</code> inside the raw string literal, you can even add more <code>#</code>s around the outside double-quotes, where you need a matching number of <code>#</code>s to make the <code>"</code> or <code>#</code> significant, e.g., <code>###" not escaped \"# until we get here "###</code>.</p></blockquote><p>Any errors that don't match that first <code>catch</code> clause will fall into the second catch clause. As a little shortcut, if the catch clause doesn't specify anything to match, it's equivalent to <code>let error</code>, i.e., it introduces local <code>error</code> value of type <code>any Error</code>.</p><p>Note that this second <code>catch</code> block throws <code>error</code> again: Swift doesn't have (nor need) a special "rethrows" syntax, because errors are just values. So if we want to "rethrow", we can <code>throw</code> the error we got. Or we can package it up---there's no need for special mechanisms like <a href="https://en.cppreference.com/w/cpp/error/exception_ptr"><code>std::exception_ptr</code></a> in C++.</p><h3><code>try?</code></h3><p>There's one last shorthand syntax to get out of the way before we switch gears a bit. If you find yourself trying an operation and producing either a value or <code>nil</code>, like this:</p><pre><code><span class="keyword">let</span> value: <span class="type">Int8</span>?
<span class="keyword">do</span> {
  value = <span class="keyword">try</span> <span class="type">Int8</span>(parsing: string)
} <span class="keyword">catch</span> {
  value = <span class="keyword">nil</span>
}
</code></pre><p>Then you can use the <code>try?</code> shorthand to simplify the code to:</p><pre><code><span class="keyword">let</span> value = <span class="keyword">try</span>? <span class="type">Int8</span>(parsing: string)
</code></pre><p>The <code>try?</code> expression performs the operation to its right and, if successful, returns its value. If the operation throws an error, then the <code>try?</code> expression returns <code>nil</code>. The type of a <code>try?</code> is an optional of the expression to its right, so in this case, we get an <code>Int?</code>. I'm not a huge fan of this feature, because it loses information about the specific error that was thrown, but it can be convenient when throwing together some Swift code to get a task done once or twice.</p><h3>Throwing closures</h3><p>Just like functions, closures can throw. Such closures can explicitly be marked with <code>throws</code> if you provide a parameter list, like this:</p><pre><code><span class="keyword">func</span> commaSeparatedIntegers(string: <span class="type">String</span>) <span class="keyword">throws</span> -&gt; [<span class="type">Int8</span>] {
  <span class="comment">// split String into [Substring] instances at the given separator</span>
  <span class="keyword">let</span> strings = string.<span class="call">split</span>(separator: <span class="string">","</span>) 
  <span class="keyword">return try</span> strings.<span class="call">map</span> { (substring: <span class="type">String</span>) <span class="keyword">throws in
    try</span> <span class="type">UInt8</span>(parsing: <span class="type">String</span>(substring))
  }
}
</code></pre><p>A few things to note: the <a href="https://developer.apple.com/documentation/swift/sequence/split(separator:maxsplits:omittingemptysubsequences:)"><code>split(separator:)</code></a> operation on a collection turns an array of subcollections that are separated by the <code>Equatable</code> element provided by the <code>separator</code> argument. In this example, we then <code>map</code> over those substrings (a <a href="https://en.cppreference.com/w/cpp/algorithm/transform"><code>std::transform</code></a> in C++ STL-speak) to parse each of them into an integer. Because the initializer of the <code>UInt8</code> <code>throws</code>, we must mark the closure's return expression with <code>try</code>. Now, when giving a throwing closure, the <code>map</code> operation itself also throws, so we need to mark the <code>map</code> call with a <code>try</code> as well. Therefore, all of the exceptional control flow (out of the closure, and out of the map call) is indicated in the program.</p><p>Now, we don't <em>have</em> to mark a closure as throwing when it throws, because it can be inferred. A closure that contains a <code>throw</code> or a <code>try</code> (that isn't swallowed up in a <code>do..catch</code> / <code>try?</code> / <code>try!</code>) is known to throw, so the above can be written more succinctly as:</p><pre><code><span class="keyword">func</span> commaSeparatedIntegers(string: <span class="type">String</span>) <span class="keyword">throws</span> -&gt; [<span class="type">Int8</span>] {
  <span class="comment">// split String into [Substring] instances at the given separator</span>
  <span class="keyword">let</span> strings = string.<span class="call">split</span>(separator: <span class="string">","</span>) 
  <span class="keyword">return try</span> strings.<span class="call">map</span> { 
    <span class="keyword">try</span> <span class="type">UInt8</span>(parsing: <span class="type">String</span>($0))
  }
}
</code></pre><p>I'm also using the <code>$0</code> shorthand for "the first closure argument", because this closure is so small that it's not worth naming the argument. The presence of <code>try</code> implies that the closure <code>throws</code>.</p><p>We're going to come back to <code>map</code> and it's "it throws if its input closure throws" behavior a bit later, when we talk about typed throws.</p><h2>Program bugs are not exceptional conditions</h2><p>We've talked a lot about the mechanics of error handling in Swift, so now let's talk some philosophy. Swift takes the viewpoint that errors are exceptional conditions that the program has to deal with, but <strong>program bugs are not exceptional conditions.</strong> When Swift detects a program bug, such as an out-of-bounds index into an array or an attempt to force an optional value containing <code>nil</code> (via <code>!</code> or <code>as!</code>), it will immediately halt the program. It will look like a program crash, but should be accompanied by a message indicating what went wrong.</p><p>The Swift philosophy, echoed by Herb's ¬ß4.2, is that a program should not attempt to recover from a programmer error. Programmer errors are likely to mean broken invariants that will cause more problems later, and a program that's limping on after a program error is ripe for security exploits. So when things go wrong, Swift halts the program to prevent further damage.</p><p>Now, you don't <em>have</em> to buy in to Swift's philosophy here. You can go ahead and add an <code>Array</code> subscript that throws when out of bounds, or a cast operation that throws when it fails, and generally turn every bad thing that can happen into a thrown error. You'll be going against the grain of the Swift standard library and general community, but it's possible. But know that I will know, and I will judge you :).</p><h3><code>try!</code></h3><p>There are some times when you're using a general operation that can throw an error, but because of where you are in the program, you <em>know</em> it can't fail. Perhaps you're working from data that's baked into the program elsewhere, or are in program startup where things can't go wrong yet. As a corollary to <code>try?</code>, there's a <code>try!</code> operation that produces a fatal error if an error is thrown from its subexpression. For example, if we do:</p><pre><code><span class="keyword">let</span> value = <span class="keyword">try</span>! <span class="type">Int8</span>(parsing: <span class="string">"1+23"</span>)
</code></pre><p>The type of the <code>try!</code> expression is the type of its subexpression; here, that's <code>Int8</code>. If an error is thrown from the subexpression, the program will halt with an error message something like this:</p><pre><code>parsing/parsing.<span class="property">swift</span>:<span class="number">94</span>: <span class="type">Fatal</span> error: '<span class="keyword">try</span>!' expression unexpectedly raised an error: parsing.<span class="type">IntegerParseError</span>.<span class="call">nonDigitCharacter</span>(<span class="string">"12+3"</span>, index: <span class="type">Swift</span>.<span class="type">String</span>.<span class="type">Index</span>(_rawBits: <span class="number">65799</span>))
</code></pre><p>You can think of <code>try!</code> as having about the same semantics as <code>(try? &lt;subexpression&gt;)!</code>, but providing a better error message when things go wrong. Unlike <code>try?</code>, I actually do like <code>try!</code>: when the program invariants say there can't be an error here, it's a lot more convenient than a <code>do..catch</code> with a <code>fatalError</code> in the <code>catch</code> block.</p><blockquote><p><strong>Aside</strong>: Some Swift style guides prohibit the use of the various <code>!</code> operations, whether they are <code>!</code> to force-unwrap optional, <code>as!</code> to force-cast, or <code>try!</code> to assert that an operation cannot fail. These constructs exist in Swift for a reason, and are appropriate to use when the surrounding program invariants ensure that the operation cannot fail, but you weren't able to express those invariants in the type system. The consistent use of <code>!</code> is meant to say "be wary", not "run away screaming."</p></blockquote><h3>Preconditions and assertions</h3><p>A careful programmer will document the invariants of data structures and the preconditions of any functions, so that misuses due to programmer error are caught quickly. To support this checking consistently, Swift provides the <code>precondition</code> function, which takes a <code>Bool</code> condition, an optional error message string, and optional file/line information (that will be automatically filled in for you). For example, a bounds check on an array subscript will use a precondition like this:</p><pre><code><span class="call">precondition</span>(index &gt;= <span class="number">0</span> &amp;&amp; index &lt; count, <span class="string">"out-of-bounds array index"</span>)
</code></pre><p>If that <code>Bool</code> expression evaluates <code>false</code>, the program will halt immediately and display the error message, line, and column. The actual declaration of <code>precondition</code> shows off a few tiny features that Swift library developers like to use, that I otherwise wouldn't have gotten to, so here it is:</p><pre><code><span class="keyword">public func</span> precondition(
  <span class="keyword">_</span> condition: <span class="keyword">@autoclosure</span> () -&gt; <span class="type">Bool</span>,
  <span class="keyword">_</span> message: <span class="keyword">@autoclosure</span> () -&gt; <span class="type">StaticString</span> = <span class="type">StaticString</span>(),
  file: <span class="type">StaticString</span> = <span class="keyword">#file</span>, line: <span class="type">UInt</span> = <span class="keyword">#line</span>
)
</code></pre><p>The first argument is the <code>Bool</code> condition, but it has <em>function</em> type and this <code>@autoclosure</code> thing. What's going on? Well, an "autoclosure" is a fun way in which a function can defer computation of one of its arguments. In essence, when we wrote the expression <code>index &gt;= 0 &amp;&amp; index &lt; count</code>, Swift packaged that up into a closure</p><pre><code>{ index &gt;= <span class="number">0</span> &amp;&amp; index &lt; count }
</code></pre><p>and passed that closure into the <code>precondition</code> function. We can evaluate the condition by calling <code>condition()</code> in the body of the function. Note that the <code>message</code> is also an <code>@autoclosure</code>: we won't call the closure unless the condition has failed, so we don't need to form the string instance except along the error path. Auto-closures actually came into being because we wanted to be able to express the short-circuiting behavior of the logical <code>&amp;&amp;</code> operation in the library. The implementation looks like this:</p><pre><code><span class="keyword">extension</span> <span class="type">Bool</span> {
  <span class="keyword">public static func</span> &amp;&amp;(lhs: <span class="type">Bool</span>, rhs: <span class="keyword">@autoclosure</span> () -&gt; <span class="type">Bool</span>) -&gt; <span class="type">Bool</span> {
    lhs ? <span class="call">rhs</span>() : <span class="keyword">false</span>
  }
}
</code></pre><p>Autoclosures are also used in Swift's <code>assert</code> function, which ensures that a particular condition holds <em>but only in debug builds</em>. In release builds, the <code>assert</code> function folds away, never evaluating the condition. Use asserts for checking invariants that are too expensive in release builds, but can help aid debugging when things go wrong:</p><pre><code><span class="call">assert</span>(<span class="keyword">self</span>.<span class="property">isSorted</span>, <span class="string">"insert operation must maintain sortedness property"</span>)
</code></pre><p>Both <code>precondition</code> and <code>assert</code> have defaulted <code>file</code> and <code>line</code> arguments. If you don't pass in a value, they take on the default values <code>#file</code> and <code>#line</code>, respectively. These are built-in macros that produce the file and line at the call site, which allows <code>precondition</code> and <code>assert</code> to point at where the failing precondition/assertion occurred in the source code.</p><h3>Arithmetic overflow is a program bug</h3><p>In the C++ community, we've spent a <em>lot</em> of time <a href="https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0907r4.html">fretting</a> over what to do about arithmetic overflow. It's been undefined behavior since the dawn of time, and undefined behavior is bad, so there's been a push to define it somehow. The most reasonable answer is to define it as basically every system out there implements it, which is <a href="https://ccrma.stanford.edu/~jos/fp/Two_s_Complement_Wrap_Around.html">two's complement wrapping</a>. That's better, but it's not great: arithmetic overflow that is guaranteed to wrap can open up security vulnerabilities if an attacker can manager to wrap a buffer index to get access to other data they shouldn't.</p><p>Swift's answer is to define arithmetic overflow as a programmer error, and trap when it occurs. You can see the effect of this by trying to pass a string for a too-large integer into our parsing initializer:</p><pre><code><span class="keyword">let</span> value = <span class="keyword">try</span> <span class="type">Int8</span>(parsing: <span class="string">"155"</span>)
</code></pre><p>The program will trap (crash) when trying to multiply 15 * 10 as an <code>Int8</code>. This is not great for our parsing function, so let's fix it!</p><p>Swift has two ways of dealing with arithmetic overflow programmatically. The first is a set of <a href="https://docs.swift.org/swift-book/documentation/the-swift-programming-language/advancedoperators/#Overflow-Operators">"wrapping" arithmetic operators</a> with the <code>&amp;</code> prefix that wrap their results according to two's complement arithmetic. If we replace the <code>*</code> and <code>+</code> in our <code>init(parsing:)</code> implementation with <code>&amp;*</code> and <code>&amp;+</code>, respectively, the crash will go away! Yay! Except that the answers are going to be wrong, because <code>try Int8(parsing: "155")</code> will now produce the result <code>-101</code>. Use the wrapping arithmetic operations when the algorithm you're implementing is designed for two's complement arithmetic, not as a "please make it not crash" hammer.</p><p>The second way of dealing with overflow is through the <code>*ReportingOverflow</code> family of methods on <code>FixedWidthInteger</code>, which form the appropriate operation and return the partial value along with a flag that indicates whether it overflowed or not. This allows us to detect an react to the overflow. Let's do that, and report the overflow via a thrown error. We can represent the failure condition with a new case in the <code>IntegerParseError</code> enum:</p><pre><code><span class="keyword">case</span> overflow(<span class="type">String</span>, any <span class="type">Numeric</span>.<span class="type">Type</span>)
</code></pre><p>Now, instead of writing <code>self * 10</code>, we can use the <code>multipliedReportingOverflow(by:)</code> operation, like this:</p><pre><code><span class="keyword">var</span> overflow: <span class="type">Bool</span>
(<span class="keyword">self</span>, overflow) = <span class="keyword">self</span>.<span class="call">multipliedReportingOverflow</span>(by: <span class="number">10</span>)
<span class="keyword">if</span> overflow {
   <span class="keyword">throw</span> <span class="type">IntegerParseError</span>.<span class="call">overflow</span>(string, <span class="type">Self</span>.<span class="keyword">self</span>)
}
</code></pre><p>It's a little verbose, but it works. I bet someone could write a nice throwing wrapper around a <code>FixedWidthInteger</code> type that makes this kind of code easier to write, but for now I'm going to go the brute-force method and also addition counterpart. The final integer-parsing operation is as follows:</p><pre><code><span class="keyword">extension</span> <span class="type">FixedWidthInteger</span> {
  <span class="keyword">init</span>(parsing string: <span class="type">String</span>) <span class="keyword">throws</span> {
    <span class="keyword">self</span> = <span class="number">0</span>
    <span class="keyword">for</span> index <span class="keyword">in</span> string.<span class="property">indices</span> {
      <span class="keyword">let</span> char = string[index]

      <span class="keyword">guard let</span> digit = char.<span class="property">wholeNumberValue</span> <span class="keyword">else</span> {
        <span class="keyword">throw</span> <span class="type">IntegerParseError</span>.<span class="call">nonDigitCharacter</span>(string, index: index)
      }

      <span class="keyword">var</span> overflow: <span class="type">Bool</span>
      (<span class="keyword">self</span>, overflow) = <span class="keyword">self</span>.<span class="call">multipliedReportingOverflow</span>(by: <span class="number">10</span>)
      <span class="keyword">if</span> overflow {
         <span class="keyword">throw</span> <span class="type">IntegerParseError</span>.<span class="call">overflow</span>(string, <span class="type">Self</span>.<span class="keyword">self</span>)
      }

      (<span class="keyword">self</span>, overflow) = <span class="keyword">self</span>.<span class="call">addingReportingOverflow</span>(<span class="type">Self</span>(digit))
      <span class="keyword">if</span> overflow {
         <span class="keyword">throw</span> <span class="type">IntegerParseError</span>.<span class="call">overflow</span>(string, <span class="type">Self</span>.<span class="keyword">self</span>)
      }
    }
  }
}
</code></pre><p>Now if we <code>try Int8(parsing: "155")</code> we'll get a thrown error that describes the failure: the value <code>"155"</code> doesn't fit into the integer type. We can even make the error nice and human-readable:</p><pre><code><span class="keyword">extension</span> <span class="type">IntegerParseError</span>: <span class="type">CustomStringConvertible</span> {
  <span class="keyword">var</span> description: <span class="type">String</span> {
    <span class="keyword">switch self</span> {
    <span class="keyword">case</span> .<span class="dotAccess">nonDigitCharacter</span>(<span class="keyword">let</span> string, <span class="keyword">let</span> index):
      <span class="string">"non-digit character '</span>\(string[index])<span class="string">' at index</span> \(index) <span class="string">when converting '</span>\(string)<span class="string">' to an integer"</span>

    <span class="keyword">case</span> .<span class="dotAccess">overflow</span>(<span class="keyword">let</span> string, <span class="keyword">let</span> type):
      <span class="string">"overflow converting '</span>\(string)<span class="string">' to integer type '</span>\(type)<span class="string">'"</span>
    }
  }
}
</code></pre><p>so we end up with this:</p><pre><code>overflow converting '<span class="number">155</span>' to integer type '<span class="type">Int8</span>'
</code></pre><p>It's definitely worth making your error types provide nice, human-readable error messages, because they're likely to propagate up to some part of the system that can't do anything better than present the error to the user. And that message is a whole lot nicer for most users than the default rendering <code>parsing.IntegerParseError.overflow("155", Swift.Int8)</code>.</p><h2>Typed throws</h2><p>Thus far, all the functions and closures we've seen have used "untyped" thows, where all errors are type-erased to <code>any Error</code>. Untyped errors are a good default: you can still pick out a specific error type using pattern-matching in a <code>catch</code> in those (generally rare) cases where you must, but most error-handling code just deals with any kind of error opaquely and safely backs out of the failed operation.</p><p>There are a few cases where untyped throws are insufficient, though:</p><ol><li>In performance-critical or very low-level code that cannot afford the runtime cost of type erasure or perhaps cannot allocate at all along the error path. This includes <a href="https://github.com/apple/swift-evolution/blob/main/visions/embedded-swift.md">Embedded Swift</a>, which doesn't allow for type erasure in any form. (Note that this restriction is captured by Herb's ¬ß4.1).</li><li>In generic code that will only propagate errors that are introduced by operations on its generic inputs, such as the <code>map</code> operation throwing an error only when its closure parameter throws.</li></ol><p>In such cases, it can be valuable to specify the exact type of the error that can be thrown. Swift allows this with typed throws, which allows one to specify a concrete thrown error type in parentheses after the <code>throws</code> keyword. Our parsing code could adopt typed throws like this:</p><pre><code><span class="keyword">init</span>(parsing string: <span class="type">String</span>) <span class="call">throws</span>(<span class="type">IntegerParseError</span>) { ... }
</code></pre><p>Now, this initializer may only throw or propagate errors of the type <code>IntegerParseError</code>. If you really want, you can take advantage of the type inference this affords for throws statements to omit the <code>IntegerParseError</code> on them, e.g.,</p><pre><code><span class="keyword">throw</span> .<span class="call">nonDigitCharacter</span>(string, index: index)
</code></pre><p>For callers, the knowledge that this initializer can only throw <code>IntegerParseError</code> gives tighter bounds for <code>do..catch</code> blocks. For example, this code knows that the caught <code>error</code> is of type <code>IntegerParseError</code>:</p><pre><code><span class="keyword">do</span> {
  <span class="keyword">let</span> value = <span class="keyword">try</span> <span class="type">Int8</span>(parsing: string)
  <span class="call">print</span>(<span class="string">"Value is</span> \(value)<span class="string">"</span>)
} <span class="keyword">catch</span> {
  <span class="comment">// error has type `IntegerParseError`</span>
}
</code></pre><p>That's the basics of typed throws: you can specify the type of a thrown error, which of course must conform to the <code>Error</code> protocol. This becomes part of the interface contract, so the implementation must only every throw this type, and clients are guaranteed to only ever see a thrown error of this type. It's all enforced statically, so you can't get it wrong. However, you can come to regret being specific about the thrown error type, if you later change the implementation in a manner that can produce new kinds of errors.</p><blockquote><p><strong>Warning</strong>: As of the time of this writing (April, 2024), typed throws has been accepted into the upcoming Swift 6.0 and is available in <a href="https://www.swift.org/download/">nightly snapshots</a>, but has not yet made it into a Swift release. While it's not terribly likely, it's possible that details may change.</p></blockquote><h3>Untyped throws</h3><p>Okay, so now we have <em>untyped</em> throws, and we have <em>typed</em> throws, so how do these relate? Fortunately, this is easy: untyped throws (spelled <code>throws</code>) is the same thing as throwing <code>any Error</code> (spelled <code>throws(any Error)</code>); it's effectively just a shorthand. A function that throws some type <code>E</code> can be converted to a function that throws <code>any Error</code>. That's it; nothing weird here. Just some syntactic sugar and an implicit conversion.</p><h3>Non-throwing functions and the <code>Never</code> type</h3><p>A <em>much</em> more interesting question is how typed throws relates to <em>non-throwing</em> functions. For that, we need to introduce another special Swift type called <code>Never</code>. There's no real equivalent to <code>Never</code> in C++, so I'll describe it from first principles. Please try not to equate it to anything in C++, because it'll create more confusion: it may sound a little like <code>void</code>, but it's not that. It may sound a little like an incomplete type, but it's not that. Enough preamble, what is it?</p><p><code>Never</code> is a type for which there can never be an instance, ever. Formally, <code>Never</code> is an <code>enum</code> with no cases, which is also called an <em>uninhabited enum</em>:</p><pre><code><span class="keyword">enum</span> Never { <span class="comment">/* empty */</span> }
</code></pre><p>Now, because there can never be an instance of type <code>Never</code>, any computation that <em>produces</em> a value of type <code>Never</code> must be unreachable. Dead code. An impossible state.</p><p><code>Never</code> came into Swift as a more composable way to indicate that a function could never return. C++11 has <a href="https://en.cppreference.com/w/cpp/language/attributes/noreturn">the <code>noreturn</code> attribute</a> to say that a function could never return, but it's an attribute tacked on to a function, and doesn't get any real checking. In Swift, we give that function the result type <code>Never</code>:</p><pre><code><span class="keyword">func</span> explode() -&gt; <span class="type">Never</span> {
  <span class="call">fatalError</span>(<span class="string">"BOOM!"</span>)
}
</code></pre><p>A <code>Never</code>-returning function must not return along any path. If any path could return or fall off the end of the function, the compiler will emit an error. The <code>explode()</code> function above is known to be correct because it's calling <code>fatalError</code>, which is defined in the Standard Library to return <code>Never</code>:</p><pre><code><span class="keyword">public func</span> fatalError(
  <span class="keyword">_</span> message: <span class="keyword">@autoclosure</span> () -&gt; <span class="type">String</span> = <span class="type">String</span>(),
  file: <span class="type">StaticString</span> = <span class="keyword">#file</span>, line: <span class="type">UInt</span> = <span class="keyword">#line</span>
) -&gt; <span class="type">Never</span>
</code></pre><p>Using the <code>Never</code> type instead of an attribute has really nice properties, because it interacts nicely with type inference. If you form a closure that calls <code>fatalError</code>, it will be inferred to have result type <code>Never</code>, so we know that calls to that closure never return. And if you call a generic function that returns a <code>T</code>, and <code>T</code> is inferred to <code>Never</code>, you know that the generic function won't return.</p><p>Let's get back to throwing. If a function isn't marked with <code>throws</code>, then it doesn't throw. One might say it... <em>never</em>... throws. Joking aside, this means that a function that <code>throws(Never)</code> is equivalent to one that does not throw. So typed throws is actually a generalization of throwing functions, where <code>throws(any Error)</code> is "can throw anything" and <code>throws(Never)</code> is "does not throw", and you can have any <code>throws(Concrete)</code> in between.</p><h3>Generic error propagation</h3><p>A bit earlier, we had this call to <code>map</code>:</p><pre><code>   <span class="keyword">return try</span> strings.<span class="call">map</span> { 
    <span class="keyword">try</span> <span class="type">UInt8</span>(parsing: <span class="type">String</span>($0))
  }
</code></pre><p>and I noted that <code>map</code> propagates the error from the closure out. Now that we have typed throws, we can express the <code>map</code> operation generically:</p><pre><code><span class="keyword">extension</span> <span class="type">Collection</span> {
  <span class="keyword">func</span> map&lt;T, E&gt;(body: (<span class="type">Element</span>) <span class="call">throws</span>(<span class="type">E</span>) -&gt; <span class="type">T</span>) <span class="call">throws</span>(<span class="type">E</span>) -&gt; [<span class="type">T</span>] {
    <span class="keyword">var</span> result: [<span class="type">T</span>] = []
    <span class="keyword">for</span> element <span class="keyword">in self</span> {
      result.<span class="call">append</span>(<span class="keyword">try</span> <span class="call">body</span>(element))
    }
    <span class="keyword">return</span> result
  }
}
</code></pre><p>The basic idea is that we're calling <code>body</code> for each element in the collection, and appending the result to the <code>result</code> array to be returned at the end. Easy.</p><p>Now, <code>body</code> can throw an error of type <code>E</code>. When it does, that error propagates out of <code>map</code>, which is <em>also</em> defined to throw type <code>E</code>. <code>E</code>, in this case, is a generic parameter that is inferred from the call site. Everything type-checks in the <code>map</code> definition because the only throwing call site produces an <code>E</code>.</p><p>Now let's look at the client. In our original <code>map</code> call</p><pre><code>   <span class="keyword">return try</span> strings.<span class="call">map</span> { 
    <span class="keyword">try</span> <span class="type">UInt8</span>(parsing: <span class="type">String</span>($0))
  }
</code></pre><p>the closure will be inferred to throw an error (<code>IntegerParseError</code>) based on the call to <code>init(parsing:)</code>. The generic argument for <code>E</code> will, therefore, be inferred to be <code>IntegerParseError</code>, so the whole <code>map</code> call throws <code>IntegerParseError</code>. What about a non-throwing case?</p><pre><code><span class="keyword">return</span> strings.<span class="call">map</span> { 
    (<span class="keyword">try</span>? <span class="type">UInt8</span>(parsing: <span class="type">String</span>($0))) ?? <span class="type">UInt8</span>(<span class="number">0</span>) <span class="comment">// turn failures into 0s</span>
  }
</code></pre><p>Here, the closure does not throw (because the error from <code>init(parsing:)</code> is swallowed by the <code>try?</code>), so it has a thrown error type of <code>Never</code>. The generic argument for <code>E</code> is inferred to <code>Never</code>, so the call to <code>map</code> is known not to throw... and we don't need a <code>try</code> outside of the call to <code>map</code>.</p><p>Operations like <code>map</code> that are expressed in terms of generic thrown error types are only considered to throw when the thrown error type is inferred to something other than <code>Never</code>, allowing them to act as either throwing or not depending on context. This abstraction over thrown error types means we don't have to duplicate generic implementations to account for throwing vs. non-throwing. <code>Never</code> may feel odd, but it's quite powerful.</p><blockquote><p><strong>Historical note</strong>: Prior to the introduction of typed throws, a different feature called <code>rethrows</code> captured the notion that a particular function would only throw when one of the closure arguments passed into it throws. This feature was used for algorithms like <code>map</code>, and is expected to rapidly fall out of favor (and probably be deprecated) once typed throws is in widespread use.</p></blockquote><h3>The <code>Result</code> type</h3><p>Swift has a standard type <a href="https://developer.apple.com/documentation/swift/result"><code>Result</code></a> type for packaging up either a successful result, or a failure condition, and is intended to be used in much the same way as <code>std::expected</code>. Personally, I've found a lot less of a need for <code>Result</code> now that Swift has <code>async</code>/<code>await</code> (the subject of a later post, I promise), but you may see it in Swift code and it's good for exposition. <code>Result</code> is an enum with two cases:</p><pre><code><span class="keyword">enum</span> Result&lt;Success, Failure: <span class="type">Error</span>&gt; {
  <span class="keyword">case</span> success(<span class="type">Success</span>)
  <span class="keyword">case</span> failure(<span class="type">Failure</span>)
}
</code></pre><p>A function that returns <code>Result&lt;T, E&gt;</code> is morally equivalent to one that returns a <code>T</code> and <code>throws(E)</code>. Indeed, one can convert in both directions fairly readily. To go from a function (or closure) to a <code>Result</code> instance, use this handy initializer:</p><pre><code><span class="keyword">extension</span> <span class="type">Result</span> {
  <span class="keyword">init</span>(catching body: () <span class="call">throws</span>(<span class="type">Failure</span>) -&gt; <span class="type">Success</span>) {
    <span class="keyword">do</span> {
      <span class="keyword">self</span> = .<span class="call">success</span>(<span class="keyword">try</span> <span class="call">body</span>())      
    } <span class="keyword">catch</span> {
      <span class="keyword">self</span> = .<span class="call">failure</span>(error)
    }
  }
}
</code></pre><p>In other words: run the body. If it succeeds, put the successful value into <code>self</code> via the <code>success</code> case. If it fails, it will have thrown an instance of type <code>Failure</code>, so the <code>catch</code> block will initialize <code>self</code> via the <code>failure</code> case. Either way, <code>self</code> is fully initialized at the end!</p><p>To go the other way, there's a <code>get</code> operation:</p><pre><code><span class="keyword">extension</span> <span class="type">Result</span> {
  <span class="keyword">func</span> get() <span class="call">throws</span>(<span class="type">Failure</span>) -&gt; <span class="type">Success</span> {
    <span class="keyword">switch self</span> {
      <span class="keyword">case</span> .<span class="dotAccess">success</span>(<span class="keyword">let</span> value): <span class="keyword">return</span> success
      <span class="keyword">case</span> .<span class="dotAccess">failure</span>(<span class="keyword">let</span> error): <span class="keyword">throw</span> error
    }
  }
}
</code></pre><p>A call to <code>get</code> will either get the success value, or throw failure. If you prefer to use property access, we can write that with a throwing computed property:</p><pre><code><span class="keyword">extension</span> <span class="type">Result</span> {
  <span class="keyword">var</span> value: <span class="type">Success</span> {
    <span class="keyword">get throws</span>(<span class="type">Failure</span>) {
      <span class="keyword">return</span> <span class="call">get</span>()
    }
  }
}
</code></pre><p><code>Result</code> illustrates another one of the great things about <code>Never</code>: if you have a type <code>Result&lt;Int, Never&gt;</code>, then it's just a wrapper around an <code>Int</code>. If you call <code>get()</code> or use <code>value</code>, it's known not to throw (because <code>Failure</code> is <code>Never</code>), so you don't need a <code>try</code>. All of the generic code just works, because it's impossible to ever end up in the <code>failure</code> case dynamically to trigger a thrown error.</p><h2>Wrap-up</h2><p>Error handling is one of the parts of Swift I adore: it's purposeful and opinioned, the pieces all compose well, and it helps take a tricky aspect of programming and makes it easier through useful application of a static type system. For C++ practitioners, there's a lot to be familiar with, because the basic model is effectively the same: thrown errors propagate up until they hit a matching catch. However, the defaults have been re-oriented to make exceptional conditions uncommon, static checking has been made sound to prevent accidents, and exceptional control flow has been made explicit to aid in understanding code.</p><p>And although it's not baked into the language design per se, Swift has definite opinions about when to throw errors and when to trap. Programmer errors should trap as soon as they are detected to prevent them from causing bad behavior, including security issues. Other exceptional conditions that prevent the normal flow of the problem should be reported as errors, preserving enough detail to provide a useful error message to be logged for the programmer or reported to the end user. I believe that following this philosophy, and being properly supported by the language in handling errors, leads to better-quality code in the long run.</p></div><span>Tagged with: </span><ul class="tag-list"><li><a href="/tags/swift">Swift</a></li><li><a href="/tags/c">C++</a></li></ul></article></div><footer><p>Generated using <a href="https://github.com/johnsundell/publish">Publish</a></p><p><a href="/feed.rss">RSS feed</a></p></footer></body></html>